### ISSUE TITLE
Menu de Configuração do Usuário

### ISSUE THREAD

**Issue by heukirne** [noharm-ai/frontend#10]
Oi querida, vou descrever a tarefa aqui, mas se tiver dúvidas a gente conversa:

- Criar, no Menu Configuração, um submenu "Usuário"
- endpoint: /user/{id} POST
- A Tela vai ter a opção de editar duas informaçoes:
   - alteração de senha: campo texto
   - configuração da assinatura: campo texto puro (memória)
   - botão de Salvar

Tu pode criar um Fork dessa repositório e já solicitar um Pull Request pra ficar associado à essa tarefa.
Quando tu avançar na tela, eu faço o endpoint pra ti.

Abração!

**Comment by Paulafranceschini** [comment]
Oie!

Eu criei um fork, mas não entendi como criar um pull-request associado à
tarefa (n tenho mta experiência com o git). Pode me dar uma ajuda?

Beijo!!

**Comment by heukirne** [comment]
Oi querida,

Quando tu fizer o primeiro commit, vai liberar pra fazer o Pull Request aqui:
![Screenshot from 2020-07-03 14-04-57](https://user-images.githubusercontent.com/97672/86488094-50d15080-bd36-11ea-9dc5-22c8fa64f1aa.png)
Daí tu dá um nome pro Pull Request, pode ser o mesmo nome da tarefa, e assim conseguimos relacionar o PR aqui. ;)
![Screenshot from 2020-07-03 14-06-47](https://user-images.githubusercontent.com/97672/86488161-7b230e00-bd36-11ea-86d3-acea3ad1b737.png)
