### ISSUE TITLE
Novos filtros no Menu Intervenção

### ISSUE THREAD

**Issue by heukirne** [noharm-ai/frontend#101]
Dae garotoo,
Uma demanda light pra semana: adicionar novos filtros no Menu Intervenção:
 - Prescritor
 - Setor
 - Motivo

Que tu acha?
Eu ainda preciso trazer as informações no endpoint.

Abrasss :wink:

**Comment by heukirne** [comment]
Já atualizei o Endpoint com o departamento e prescritor. :kissing_heart: 
O motivo, pode começar filtrando só o primeiro do array pra facilitar.

**Comment by marceloarocha** [comment]
Done!

**Comment by heukirne** [comment]
Valeuuu!!!
