### ISSUE TITLE
Bug no Progresso do Escore

### ISSUE THREAD

**Issue by heukirne** [noharm-ai/frontend#107]
Dae garoto, vê se isso é simples ou se precisa de simulação no backend.

Tem algum bug no [cáculo do pencentual](https://github.com/noharm-ai/frontend/blob/f25174381834aead4cce07aa88a00f0914b51132/src/components/Segments/index.jsx#L76). Esse hospital tinha 65 partes, quando chegou na 50ª chamada, ele fechou os 100%, mas continuou rodando os demais e só depois que finalizou que fechou o modal.

:wink:

**Comment by marceloarocha** [comment]
Fixed ;)
