### ISSUE TITLE
Erro ao Resolver Intervenção dentro do Medicamento

### ISSUE THREAD

**Issue by heukirne** [noharm-ai/frontend#55]
Ao clicar em Aceitar uma intervenção, dentro da linha extendida de um medicamentos, dá o erro abaixo:
![Screenshot from 2021-01-05 16-23-10](https://user-images.githubusercontent.com/97672/103690020-db5b6c80-4f72-11eb-8c91-e25c92bd5341.png)
:innocent:

**Comment by marceloarocha** [comment]
fixed ;)
