### ISSUE TITLE
Novo Status da Intervenção

### ISSUE THREAD

**Issue by heukirne** [noharm-ai/frontend#62]
Oi queridoo!! Mais um sprint _ultra-light_!

- Adicionar novo status na resolução de intervenção: "Não Aceite com Justificativa" char('j') "jota minúsculo"

Já ohei no backend e não precisa fazer nenhuma alteração. É só frontend e relatórios.

Beijooos :kissing_heart:

**Comment by marceloarocha** [comment]
Eae eaee!

Quando eu marco uma intervenção como "Não aceita com Justificativa", o backend para de trazer a intervenção na **aba** Intervenções,  na **página** Intervenções e na linha estendida do medicamento. Consegue dar uma olhada? (atendimento: 2007100012865726 - banco de teste)

**Comment by heukirne** [comment]
Verdade, tinha um ponto pra [adicionar o status](https://github.com/noharm-ai/backend/commit/e169fa3fc36f4870315852e11fe6e0b358fd75b8). Feito!
