### ISSUE TITLE
NoHarm White Label

### ISSUE THREAD

**Issue by heukirne** [noharm-ai/frontend#73]
Desenvolver a tela da prescrição com possibilidade de acesso via client-api com autenticação via token.

 - Criar novo branch white-label
 - Publicar branch em dev somente
 - Abrir a tela de prescrição (somente a tabela/aba de medicamentos) num iframe (endpoint sem auth)
 - Método de backend para criar prescrição em dev (sem auth)

Ex.: https://ajuda.memed.com.br/pt-BR/articles/2519616-1-passo-a-passo-para-integracao

**Comment by marceloarocha** [comment]
Finalizados:

- Tela isolada de medicamentos prescritos (sem auth);
- Tradução inicial da lista de medicamentos

Próxima task: 

- Estudar como vamos implementar a autenticação...

**Comment by heukirne** [comment]
Maravilhaaa!!
