### ISSUE TITLE
Conciliação Medicamentosa

### ISSUE THREAD

**Issue by heukirne** [noharm-ai/frontend#76]
Dae garoto!!!
Acho que podemos fazer uma entrega mais consistente para a funcionalidade da Conciliação Medicamentosa.

Seria um submenu da Priorização, chamado "das Conciliações"
 - Lista todas as Conciliações por data, com os mesmos filtros e ordenamentos atuais
 - Novo campo prescrição.conciliação char(1): tipos de conciliação _(backend)_
 - Submenu só aparece se estiver liberado para o Hospital (roles: ["conciliation"] )

Ao clicar em ver detalhes, a farma vai para a tela da Concilicação do Paciente:
 - Comparar Prescrição Vigente (à esquerda) com a Conciliação (à direita);
 - Pode fazer intervenções na Conciliação e gerar Evolução de Conciliação;
 - Existe medicamentos novos com nomes inseridos manualmente na Conciliação; _(backend)_
 - Iniciar a comparação de medicamentos pelas substâncias; _(backend)_

Podemos conversar melhor com a Ana sobre como seria a melhor forma de fazer essa tela.
Abraçoooos

**Comment by heukirne** [comment]
Demandas Backend:
 - Parâmetro novo na busca de priorização
 - Indicador de Conciliação na Prescrição
 - Uma propriedade nova com a lista de medicamentos (Med + Dose + Frequencia)
 - Nova propriedade no medicamento com a relação correta na lista

**Comment by marceloarocha** [comment]
- [ ] Novo template para evolução de conciliação
