### ISSUE TITLE
Exames Textuais (aba de exames)

### ISSUE THREAD

**Issue by heukirne** [noharm-ai/frontend#77]
Estrutura de Exames Textuais:
 - slug(nome do exame)
    - text: true
    - date: data do último
    - ref: left(último texto, 20)
    - name: Nome do exames
    - history:
       - date: data
       - value: texto completo

**Comment by marceloarocha** [comment]
Interface done! No review eu valido com a Ana!

Um detalhe: me parece que os exames não estão vindo ordenados pela data. Acho que seria interessante! Tanto na lista de exames quanto no histórico de cada exame. Que tu acha?

**Comment by heukirne** [comment]
Ordenei pela data do exame! :wink:
